import type { DbClient, DbTransaction } from "@/lib/db";
import { logger } from "@/lib/logger";

/** Postgres serialization_failure. The only error class worth retrying here. */
const SERIALIZATION_FAILURE = "40001";
/** Postgres deadlock_detected. Same treatment: the transaction can be replayed. */
const DEADLOCK_DETECTED = "40P01";

const MAX_ATTEMPTS = 5;

function retryableCode(error: unknown): string | null {
  if (typeof error !== "object" || error === null) return null;
  const code = (error as { code?: unknown }).code;
  if (code === SERIALIZATION_FAILURE || code === DEADLOCK_DETECTED) return code;
  return null;
}

/**
 * Run `body` in a SERIALIZABLE transaction, retrying on 40001 up to 5 attempts.
 *
 * BECAUSE IT RETRIES, THE BODY MUST BE IDEMPOTENT. A body that runs twice must
 * leave the same state as a body that runs once, which in practice means:
 *
 *  - inserts use ON CONFLICT (`.onConflictDoNothing()` / `.onConflictDoUpdate()`)
 *  - deletes target exact keys, never "the first N rows"
 *  - ids are generated by the CALLER, outside this function, so a replay reuses
 *    the same id instead of minting a second row
 *  - no side effects outside the database: no email, no queue publish, no
 *    counter in module scope. Those go after the transaction resolves.
 *
 * Reads that do not need serialization should not come through here; the
 * default READ COMMITTED is cheaper and never aborts.
 */
export async function runSerializable<T>(
  db: DbClient,
  body: (tx: DbTransaction) => Promise<T>,
): Promise<T> {
  let lastError: unknown;

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      return await db.transaction((tx) => body(tx), { isolationLevel: "serializable" });
    } catch (error) {
      const code = retryableCode(error);
      if (!code) throw error;

      lastError = error;
      logger.warn(
        { attempt, maxAttempts: MAX_ATTEMPTS, code },
        "serializable transaction aborted, retrying",
      );

      if (attempt < MAX_ATTEMPTS) {
        // Jittered backoff. Two transactions that keep colliding on a fixed
        // delay will collide again on the retry.
        const backoffMs = Math.min(2 ** attempt * 5, 100) * (0.5 + Math.random());
        await new Promise((resolve) => setTimeout(resolve, backoffMs));
      }
    }
  }

  logger.error({ maxAttempts: MAX_ATTEMPTS }, "serializable transaction exhausted its retries");
  throw lastError;
}
