import { and, asc, eq, inArray, sql } from "drizzle-orm";
import type { DbExecutor } from "@/lib/db";
import { countAll, idList } from "@/lib/db/sql";
import { notes, type NoteRow } from "@/lib/db/schema/notes";

/**
 * Layer 1. The ONLY module allowed to touch the `notes` table.
 *
 * Every function takes a DbExecutor, never a DbClient, so identical code runs
 * against the pooled client and inside a transaction with no branching. Nothing
 * here knows about sessions, Zod, or HTTP; the ownership predicate is passed in
 * as `userId` and enforced in the WHERE clause of every single query.
 */

export type NoteInsert = {
  id: string;
  userId: string;
  notebookId: string;
  title: string;
  body: string;
  position: number;
  wordCount: number;
};

export type NoteUpdate = Partial<{
  title: string;
  body: string;
  archived: boolean;
  position: number;
  wordCount: number;
}>;

/**
 * List one user's notes in one notebook, filtered by archived state.
 *
 * Uses the relational API (`query.notes.findMany`) rather than select(), per the
 * database rules. `userId` is in the predicate, not checked afterwards, so
 * another user's rows are invisible rather than fetched-then-filtered.
 */
export async function listNotes(
  db: DbExecutor,
  params: { userId: string; notebookId: string; archived: boolean },
): Promise<NoteRow[]> {
  return db.query.notes.findMany({
    where: and(
      eq(notes.userId, params.userId),
      eq(notes.notebookId, params.notebookId),
      eq(notes.archived, params.archived),
    ),
    orderBy: [asc(notes.position), asc(notes.id)],
  });
}

/** A single note, scoped to its owner. Returns undefined for someone else's row. */
export async function findNote(
  db: DbExecutor,
  params: { userId: string; noteId: string },
): Promise<NoteRow | undefined> {
  return db.query.notes.findFirst({
    where: and(eq(notes.id, params.noteId), eq(notes.userId, params.userId)),
  });
}

/**
 * Fetch many notes by id in one round trip.
 *
 * `inArray` is Drizzle's own helper and parameterizes correctly. The raw-SQL
 * equivalent is where the postgres-js array trap lives; see findNotesByIdsRaw
 * below for the fragment version and src/lib/db/sql.ts for why.
 *
 * An EMPTY `noteIds` means "match nothing", so this short circuits instead of
 * building a predicate. That is the caller-side discipline idList() documents.
 */
export async function findNotesByIds(
  db: DbExecutor,
  params: { userId: string; noteIds: readonly string[] },
): Promise<NoteRow[]> {
  if (params.noteIds.length === 0) return [];
  return db.query.notes.findMany({
    where: and(eq(notes.userId, params.userId), inArray(notes.id, [...params.noteIds])),
  });
}

/**
 * The same fetch expressed in raw SQL, kept because reorder needs a single
 * statement with a VALUES join and this is the pattern that has to be right.
 *
 * `idList()` builds N bound placeholders. Binding the array itself
 * (`= ANY(${ids})`) is the trap: postgres-js passes it as one parameter and
 * Postgres raises "malformed array literal".
 *
 * Short circuits on empty for the same reason as above: idList([]) is TRUE, so
 * an empty list would match every one of this user's notes.
 */
export async function findNotesByIdsRaw(
  db: DbExecutor,
  params: { userId: string; noteIds: readonly string[] },
): Promise<NoteRow[]> {
  if (params.noteIds.length === 0) return [];
  const rows = await db.execute<NoteRow>(sql`
    SELECT * FROM ${notes}
    WHERE ${notes.userId} = ${params.userId}
      AND ${notes.id} IN ${idList(params.noteIds)}
  `);
  return rows as unknown as NoteRow[];
}

/** Count a user's notes in a scope. Cast to int; a bigint arrives as a string. */
export async function countNotes(
  db: DbExecutor,
  params: { userId: string; notebookId: string; archived: boolean },
): Promise<number> {
  const [row] = await db
    .select({ total: countAll })
    .from(notes)
    .where(
      and(
        eq(notes.userId, params.userId),
        eq(notes.notebookId, params.notebookId),
        eq(notes.archived, params.archived),
      ),
    );
  return row?.total ?? 0;
}

/**
 * Insert a note.
 *
 * ON CONFLICT DO NOTHING plus a returning-or-refetch, so the whole call is
 * idempotent and safe inside runSerializable's retry loop: `id` is generated by
 * the caller, so a replay writes the same row rather than a second one.
 */
export async function insertNote(db: DbExecutor, values: NoteInsert): Promise<NoteRow> {
  const [inserted] = await db
    .insert(notes)
    .values(values)
    .onConflictDoNothing({ target: notes.id })
    .returning();

  if (inserted) return inserted;

  // The retry case: the row already landed on a previous attempt.
  const existing = await findNote(db, { userId: values.userId, noteId: values.id });
  if (!existing) {
    throw new Error(`insertNote: note ${values.id} neither inserted nor found`);
  }
  return existing;
}

/**
 * Patch a note, scoped to its owner. Returns undefined when nothing matched,
 * which the service turns into NotFoundError. Idempotent: the same patch applied
 * twice produces the same row.
 */
export async function updateNote(
  db: DbExecutor,
  params: { userId: string; noteId: string; patch: NoteUpdate },
): Promise<NoteRow | undefined> {
  const [updated] = await db
    .update(notes)
    .set({ ...params.patch, updatedAt: new Date() })
    .where(and(eq(notes.id, params.noteId), eq(notes.userId, params.userId)))
    .returning();
  return updated;
}

/**
 * Set positions for several notes at once, by exact key.
 *
 * Exact-key updates, so replaying this inside a retried transaction converges to
 * the same order rather than shuffling further. Short circuits on empty.
 */
export async function setNotePositions(
  db: DbExecutor,
  params: { userId: string; positions: readonly { id: string; position: number }[] },
): Promise<number> {
  if (params.positions.length === 0) return 0;

  let touched = 0;
  for (const { id, position } of params.positions) {
    const updated = await updateNote(db, {
      userId: params.userId,
      noteId: id,
      patch: { position },
    });
    if (updated) touched += 1;
  }
  return touched;
}

/**
 * Delete by exact key. Returns whether a row was removed, so a replay inside a
 * retried transaction reports false the second time rather than failing.
 */
export async function deleteNote(
  db: DbExecutor,
  params: { userId: string; noteId: string },
): Promise<boolean> {
  const deleted = await db
    .delete(notes)
    .where(and(eq(notes.id, params.noteId), eq(notes.userId, params.userId)))
    .returning({ id: notes.id });
  return deleted.length > 0;
}

/** Count notes in a notebook sharing a title, for the duplicate soft warning. */
export async function countNotesWithTitle(
  db: DbExecutor,
  params: { userId: string; notebookId: string; title: string },
): Promise<number> {
  const [row] = await db
    .select({ total: countAll })
    .from(notes)
    .where(
      and(
        eq(notes.userId, params.userId),
        eq(notes.notebookId, params.notebookId),
        eq(notes.title, params.title),
      ),
    );
  return row?.total ?? 0;
}
